model_configurations:
  load_bert_from_local: False
  local_bert_model_path: 
  remote_bert_model_path: dslim/bert-base-NER

dataset_configurations:
  data_file_path: data\raw_partner_headlines_tiny.csv
  entity_confidence_score: 0.7
  extra_domain_words_path: domain_related_words.yaml
  dump_domain_words: True
  preload_domain_words: True
  content_name: news_headlines
  most_common_words_count: 50
  generate_domain_words: True